# Site Build Settings

# jekyll-paginate configuration
paginate:            5
url: https://www.tjg.me.uk

#permalink: pretty # /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Tom Glover"
description:	       "a personal blog for all the ramblings"
author:              "Tom Glover"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
